version: '3'
services:
  db:
    image: postgres:13-alpine
    container_name: database
    ports:
      - "5430:5432"
    env_file:
      - ./deployment/database.env

  ui:
    container_name: frontend
    build:
      context: ./
      dockerfile: ./deployment/Dockerfile.frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    container_name: backend
    build:
      context: ./
      dockerfile: ./deployment/Dockerfile.backend
    ports:
      - "8080:8080"
    env_file:
      - ./deployment/backend.env
    depends_on:
      - db