version: '3'
services:
  frontend:
    build:
      context: ./ui
    ports:
      - "3000:3000"
  backend:
    build:
      context: ./api
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: steam_items
