version: '3'
services:
  db:
    image: postgres:latest
    container_name: database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: steam_items

  backend:
    container_name: backend
    build:
      context: ./api
    ports:
      - "8080:8080"
    environment:
      DATABASE_HOSTNAME: localhost
      DATABASE_PORT: 5432
      DATABASE_PASSWORD: admin
      DATABASE_NAME: steam_items
      DATABASE_USERNAME: admin
    depends_on:
      - db

  ui:
    container_name: frontend
    build:
      context: ./ui
    ports:
      - "3000:3000"
    depends_on:
      - backend