/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from "@tanstack/react-router";

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as ItemsIndexImport } from "./routes/items/index";
import { Route as ItemsItemIdImport } from "./routes/items/$itemId";

// Create Virtual Routes

const IndexLazyImport = createFileRoute("/")();

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: "/",
  getParentRoute: () => rootRoute,
} as any).lazy(() => import("./routes/index.lazy").then((d) => d.Route));

const ItemsIndexRoute = ItemsIndexImport.update({
  path: "/items/",
  getParentRoute: () => rootRoute,
} as any).lazy(() => import("./routes/items/index.lazy").then((d) => d.Route));

const ItemsItemIdRoute = ItemsItemIdImport.update({
  path: "/items/$itemId",
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import("./routes/items/$itemId.lazy").then((d) => d.Route),
);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      preLoaderRoute: typeof IndexLazyImport;
      parentRoute: typeof rootRoute;
    };
    "/items/$itemId": {
      preLoaderRoute: typeof ItemsItemIdImport;
      parentRoute: typeof rootRoute;
    };
    "/items/": {
      preLoaderRoute: typeof ItemsIndexImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  ItemsItemIdRoute,
  ItemsIndexRoute,
]);

/* prettier-ignore-end */
