FROM python:3.10-alpine

WORKDIR /code

COPY ./api/requirements.txt .
RUN pip install -r requirements.txt

COPY ./api ./app

EXPOSE 8080

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080"]
