"""create items table

Revision ID: bfa2a8dba29f
Revises: 
Create Date: 2024-03-10 18:33:22.750478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfa2a8dba29f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('alphabetical_order', sa.Integer(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('weapon', 'case', 'key', 'sticker', 'graffiti', 'music_kit', 'agent', name='itemtype'), nullable=False),
    sa.PrimaryKeyConstraint('item_id'),
    sa.UniqueConstraint('full_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('items')
    # ### end Alembic commands ###
