name: UI workflow

on:
  pull_request:
    branches: [ "main" ]
    paths: [ "ui/**" ]

permissions:
  contents: read

jobs:
  check-linters:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ui
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: install
        run: npm ci
      - name: ESLint
        run: npx eslint .
      - name: Prettier
        run: npx prettier . --check